Update Courses Hashmap in plugin.rb
codewizardshq/CWHQ-Discourse-Bot pull request #15
Opened 2022-05-31 19:06 UTC by Astr0clad

Added the following to the courses hashmap in plugin.rb:
- e11_scratch_00
- e12_scratch_00
- e13_text_prog_00
- e20_prog_fundamentals_00
- e23_wd2_00
- e24_python_game_dev_00
- m12_python_beyond_basics_00
- m13_html_c22_00
- m15_web_dev_00
- h112_intro_python_00
- h14_capstone_00
- h21_api_00
- h22_web_app_00
- h23_css_framework_00
- h24_capstone00
- h31_mvc_00
- h32_orm_00
- h33_devops_00
- h34_capstone_00

I believe I have covered everything. I added everything from Daniel's post and then covered everything else from Elementary up to High School Internship. I am unable to test this so let me know if anything needs to be changed.

2022-05-31 22:55 UTC, daniel-schroeder-dev requested changes
Great work! Make those changes I suggested and we'll merge this in. I'll let you know as soon as I know what the m21 URL should be.

2022-05-31 22:55 UTC, daniel-schroeder-dev commented on plugin.rb
> +    89 => "m15_web_dev_00",
This will be m21_something_something_00. Let me ask the new Curriculum Developer what the URL structure is and we can update.

2022-05-31 22:55 UTC, daniel-schroeder-dev commented on plugin.rb
> +    11 => "e11_scratch_00",
Both Scratch courses should have URLs like this: https://scratch.mit.edu/projects/[PROJECT_ID_NUMBER]/

2022-05-31 22:55 UTC, daniel-schroeder-dev commented on plugin.rb
> +    57 => "e12_scratch_00",
Both Scratch courses should have URLs like this: [https://scratch.mit.edu/projects/[PROJECT_ID_NUMBER]/](https://scratch.mit.edu/projects/%5BPROJECT_ID_NUMBER%5D/)

2022-05-31 22:55 UTC, daniel-schroeder-dev commented on plugin.rb
> +    11 => false
Remove this, since we can use the Scratch URL I provided above.

2022-05-31 23:47 UTC, daniel-schroeder-dev commented on plugin.rb
> +    89 => "m15_web_dev_00",
Here's the URL: m21_resp_web_dev_00

2022-05-31 23:51 UTC, cmontigel commented on plugin.rb
> +    57 => "e12_scratch_00",
Do you mean having the hash look like this: `11 => https://scratch.mit.edu/projects/e_11_scratch_00/` or like `11 => https://scratch.mit.edu/projects/11/`? I'm guessing it is something completely different, and I cannot read today :eyes:.

2022-06-01 12:54 UTC, cmontigel commented
Updated the file with the requested changes. I also resolved the conversations.

2022-06-01 17:56 UTC, daniel-schroeder-dev approved these changes
Great work, thanks for contributing!

2022-06-01 17:56 UTC, merged